### ISSUE TITLE
App gets stuck on CircularProgressIndicator

### ISSUE THREAD

**Issue by mrmayurgithub** [bharat-1809/JustSplit#7]
App gets stuck on CircularProgressIndicator whenever internet connection is unavailable. When we try to update, delete or add any expense on the app, the app gets stuck on the CircularProgressIndicator and it doesn't show any Network Error. 
So, the users will not know that there is a network problem.

**Comment by bharat-1809** [comment]
Sure! @mrmayurgithub go ahead. You can use `SnackBar` to display the error message
